INSERT INTO users (name, age) VALUES ("Mark",2);
INSERT INTO users (name, age) VALUES ("Hana",2);
INSERT INTO users (name, age) VALUES ("Nona",24);
INSERT INTO users (name, age) VALUES ("Lil' Jon",28);
INSERT INTO users (name, age) VALUES ("a",2);
INSERT INTO users (name, age) VALUES ("b",2);
INSERT INTO users (name, age) VALUES ("c",24);
INSERT INTO users (name, age) VALUES ("d",28);
INSERT INTO users (name, age) VALUES ("e",2);
INSERT INTO users (name, age) VALUES ("f",2);
INSERT INTO users (name, age) VALUES ("g",24);
INSERT INTO users (name, age) VALUES ("h",28);
INSERT INTO users (name, age) VALUES ("i",2);
INSERT INTO users (name, age) VALUES ("j",2);
INSERT INTO users (name, age) VALUES ("k",24);
INSERT INTO users (name, age) VALUES ("L",28);
INSERT INTO users (name, age) VALUES ("M",2);
INSERT INTO users (name, age) VALUES ("N",2);
INSERT INTO users (name, age) VALUES ("o",24);
INSERT INTO users (name, age) VALUES ("p",28);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("BIG WILLY STYLE", "Getting Jiggy With it", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("BIGGER WILLY STYLE", "Getting Jiggy With it", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("BIGGEST WILLY STYLE", "Education", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SUPERIOR WILLY STYLE", "Education", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("PERFECTED WILL STYLE", "Getting Jiggy With it", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("INEFFABLE WILLY STYLE", "Getting Jiggy With it", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("THE STYLE OF WILLY", "Education", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("FREE WILLY", "Getting Jiggy With it", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("WILLY WONKA AND THE BIG WILLY STYLE FACTORY", "Getting Jiggy With it", 100000000, "06-07-1989", "02-22-2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("WILLY STYLE THROUGH THE AGES", "Getting Jiggy With it", 100000000, "06-07-1989", "02-22-2022");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 2, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 3, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 4, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 5, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 6, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 8, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 9, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 10, 1);